# map legacy app running in one vm
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  namespace: vm
  name: test2-vm1
spec:
  # serviceAccount: vm-access
  address: 10.1.4.4
  labels:
    app: test2
    instance-id: vm1

---
# # map legacy app running in another vm
# apiVersion: networking.istio.io/v1alpha3
# kind: WorkloadEntry
# metadata:
#   namespace: vm
#   name: test2-vm2
# spec:
#   # serviceAccount: vm-access
#   address: 10.1.4.100
#   labels:
#     app: test2
#     instance-id: vm2

# ---
# load balance requests between them by targeting the labels.
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  namespace: vm
  name: test2-legacy1
spec:
  hosts:
  - test2-legacy1.service
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 80
  resolution: STATIC
  # target any workload running either in VM or in a POD having this label. Good for migrations. 
  workloadSelector:
    labels:
      app: test2