apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  namespace: vm
  name: test2-app1-vm1
spec:
  serviceAccount: vm-access
  address: 10.1.4.4
  labels:
    app: test2-app1

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  namespace: vm
  name: test2-app1
spec:
  hosts:
  - test2-app1.service
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 80
  resolution: STATIC
  workloadSelector:
    labels:
      app: test2-app1