
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  namespace: vm
  name: test3-app1-vm1
spec:
  # serviceAccount: vm-access
  address: 10.1.4.4
  labels:
    app: test3-app1

---
apiVersion: v1
kind: Service
metadata:
  namespace: vm
  name: test3-app1
  labels:
    app: test3-app1
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: test3-app1