
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  namespace: vm
  name: test3-legacy-vm1
spec:
  # serviceAccount: vm-access
  address: 10.1.4.4
  labels:
    app: test3

---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  namespace: vm
  name: test3-legacy-vm2
spec:
  serviceAccount: vm-access # traffic over mtls
  address: 10.1.4.100
  labels:
    app: test3

---
apiVersion: v1
kind: Service
metadata:
  namespace: vm
  name: test3
  labels:
    app: test3
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: test3